### ISSUE TITLE
Notification Information Incomplete

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#101]
I had a notification that someone wanted to join my pack, but when I open the notification I am not told who wants to join.  See screen shot below

![image](https://cloud.githubusercontent.com/assets/12958622/15789996/fbd57218-299c-11e6-9e79-58e70ec96fe8.png)

**Comment by zakwhit** [comment]
I looked into this and this was a friend request from Danny. There is no name or image because he never entered these in the account settings for his dog.

Do we want to have a default dog picture and name? Or force people to add these in order to make pack requests. There is a default dog picture so I'm wondering if he removed it.

**Comment by gudell** [comment]
Thanks Zak.  I think that we had better make sure that people have this information in their profile before they make a request.  Otherwise, they may send a request, the person on the other end may not accept the request and both will think our application is broken.  I think is we force them to add missing data we accomplish 2 things.  They should also have to have this information in order to leave a review.  That way the community and the vendors know who the information is coming from.

Thanks….

Galen Udell | Founder & Top Dog | 
www.barknyapp.com http://www.barknyapp.com/ - Dog’s Best Friend
Phone: 416-434-9255
galen@barknyapp.com mailto:galen@barknyapp.com

**Comment by gudell** [comment]
Appears that all fields are now mandatory, so this item should not be an issue.  Will continue to test
