### ISSUE TITLE
Subscription Payments

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#57]
If a user clicks on the Pack Leader option, in Billing and Subscription we would like to present them with a page saying:

"This feature will be available shortly we'll contact you when its available."

This should put a "Wants to Subscribe" or some such thing mark in a field in the database so we can find and find and reach to to them later.

**Comment by zakwhit** [comment]
I was thinking that we could just send a promotional email to all of our registered vendors once the subscription tier is complete instead of trying to keep track of which vendors tried to click on a subscribed account. I feel like most people will click the subscribed button out of curiosity and so it might not be an accurate way of tracking the intent of a vendor to subscribe.

**Comment by zakwhit** [comment]
I thought that I might just put an overlay over the credit card information that says "This feature will be available shortly we'll contact you when its available..." when they try to click subscribe.

**Comment by gudell** [comment]
Zak, will we new able to track the vendors that click on this option before our payment system is in place?  I believe that the only place they can click on this is from their registered account, so I suspect we should be able to track this.

Thanks….

Galen Udell | Founder & Top Dog | 
www.barknyapp.com http://www.barknyapp.com/ - Dog’s Best Friend
Phone: 416-434-9255
galen@barknyapp.com mailto:galen@barknyapp.com
